### ISSUE TITLE
range for float values

### ISSUE THREAD

**Issue by diogoduartec** [codingconcepts/dg#7]
It would be nice to have the feature to generate float values in a specific range.

Example:
```yaml
tables:
  - name: mytable
    columns:
      - name: net
        type: range
        processor:
          type: float
          from: 10.0
          to: 100000.0
```
